[tool.poetry]
name = "igs-growth-temperatures"
version = "0.1.0"
description = "A data pipeline to integrate growth temperatures with growth run and yield data"
authors = ["Del Middlemiss <derekmiddlemiss@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.4.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
