name: Bump version and tag

on:
  push:
    branches:
      - main

env:
  COVERAGE_THRESHOLD: 80

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Linting
        shell: bash
        run: poetry run flake8

      - name: Run unit tests with coverage
        shell: bash
        run: poetry run pytest --cov=growth_job_pipeline --cov-fail-under $COVERAGE_THRESHOLD

  bump-version-tag:
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: write
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install poetry
        shell: bash
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true

      - name: Check poetry lock
        shell: bash
        run: poetry lock --check

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Bump version
        shell: bash
        run: poetry version patch

      - name: Get new version after bump
        shell: bash
        run: echo "bumped_version=$(poetry version -s)" >> $GITHUB_ENV

      - name: Tag and commit
        shell: bash
        run: |
          git config user.name "githubactions"
          git config user.email "githubactions@github.com"
          git add pyproject.toml
          git add growth_job_pipeline/__init__.py
          git commit -m "bump version"
          git tag -a v${{ env.bumped_version }} -m "v${{ env.bumped_version }}"
          git push --follow-tags origin main
